name: URide
description: A Flutter UI identical to provided mockup
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  url_launcher: ^6.2.5
  latlong2: ^0.9.0
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
    - assets/icons/
    - assets/images/motor-clicked.png
    - assets/images/mobil-clicked.png 
    - assets/images/motor-default.png
    - assets/images/mobil-default.png
    - assets/images/bengkel.png
    - assets/images/normal.png
    - assets/images/emergency.png
    - assets/images/derek.png
    - assets/images/arrow.png
    - assets/images/call.png
    - assets/images/message.png