name: uride
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  share_plus: ^12.0.1
  auto_size_text: ^3.0.0
  geolocator: ^12.0.0
  url_launcher: ^6.2.5
  http: ^1.2.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.4
  flutter_markdown: ^0.6.17
  midtrans_sdk: ^1.2.0
  geocoding: ^2.1.0
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Euclid
      fonts:
        - asset: assets/euclid-circular-a/Euclid Circular A Regular.ttf
        - asset: assets/euclid-circular-a/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/euclid-circular-a/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/euclid-circular-a/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/euclid-circular-a/Euclid Circular A Light.ttf
          weight: 300
